slack:
  webhooks:
    test1: # key is your choice
      url: # that's webhook url - exclude https://hooks.slack.com/services
    test2: # key is your choice
      url: # that's webhook url - exclude https://hooks.slack.com/services
